# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  name: Local-AzureDevOps-Openshift

stages:
- stage: CI
  displayName: CI
  jobs:
  - job: Build_Images
    displayName: Build & Push image
    steps:
    - task: AzureCLI@2
      displayName: 'acr login'
      inputs:
        azureSubscription: 'Microsoft Partner Network (48b47fa2-e2d4-4eb4-92be-f7410898af0b)'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name acrazuredevopsopenshift.azurecr.io
    - task: DockerCompose@0
      displayName: 'Build images'
      inputs:
        action: 'Build services'
    - task: DockerCompose@0
      displayName: 'Push images'
      inputs:
        action: 'Push services'
- stage: CD
  dependsOn: CI
  displayName: CD
  jobs:
  - job: Deploy_Images
    displayName: Deploy application    
    variables:
      openshift.user: 'kubeadmin'
      openshift.pass: '39ZXp-mkCfh-3XCtL-ojFMJ'
      openshift.url: 'https://api.crc.testing:6443'
    steps:
    - powershell: |
        & crc oc-env | Invoke-Expression
        oc login -u $(openshift.user) -p $(openshift.pass) $(openshift.url)
        oc project azuredevopsopenshift
        oc apply -f .\openshift\service.yaml
        displayName: 'deploy service'
    - powershell: |
        & crc oc-env | Invoke-Expression
        oc login -u $(openshift.user) -p $(openshift.pass) $(openshift.url)
        oc project azuredevopsopenshift
        oc apply -f .\openshift\client.yaml
        displayName: 'deploy client'
