# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  name: Local-AzureDevOps-Openshift

stages:
- stage: CI
  displayName: Build & Push image
  jobs:
  - job: Build_Images
    displayName: Build & Push image
    steps:
    - task: AzureCLI@2
      displayName: 'acr login'
      inputs:
        azureSubscription: 'Microsoft Partner Network (48b47fa2-e2d4-4eb4-92be-f7410898af0b)'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name acrazuredevopsopenshift.azurecr.io
    - task: DockerCompose@0
      displayName: 'Build images'
      inputs:
        action: 'Build services'
    - task: DockerCompose@0
      displayName: 'Push images'
      inputs:
        action: 'Push services'